### ISSUE TITLE
db.set_profiling_level wants different number of arguments

### ISSUE THREAD

**Issue by handlers** [sunlightlabs/mongoprof#2]
When running `mongoprof.py`, I'm getting the following:

```
Traceback (most recent call last):
  File "/Users/samh/Envs/congress/bin/mongoprof.py", line 10, in <module>
    execfile(__file__)
  File "/Users/samh/Envs/congress/src/mongoprof/mongoprof.py", line 82, in <module>
    main()
  File "/Users/samh/Envs/congress/src/mongoprof/mongoprof.py", line 78, in main
    watch(args.host, args.dbname, 0.1, args.slowms)
  File "/Users/samh/Envs/congress/src/mongoprof/mongoprof.py", line 21, in watch
    db.set_profiling_level(1 if slowms else 2, slowms or 100)
TypeError: set_profiling_level() takes exactly 2 arguments (3 given)
```
PyMongo [docs](http://api.mongodb.org/python/current/api/pymongo/database.html#pymongo.database.Database.set_profiling_level) show one mandatory and one optional argument on the method. I'm only having luck running what's effectively `db.set_profiling_level(1)`.

h/t @paultag

**Comment by jamesturk** [comment]
hm trying to replicate this one. what's the command line invocation that's failing?

**Comment by handlers** [comment]
So I re-pip installed `pymongo` and can no longer replicate this, either. Unsatisfying, but it seems safe to close this issue.

**Comment by jamesturk** [comment]
thanks, I'll close for now, let me know if anything resurfaces
